# GitHub Labels Configuration
labels:
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"
  - name: "duplicate"
    color: "cfd3d7"
    description: "This issue or pull request already exists"
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"
  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"
  - name: "invalid"
    color: "e4e669"
    description: "Something isn't right"
  - name: "question"
    color: "d876e3"
    description: "Further information is requested"
  - name: "wontfix"
    color: "ffffff"
    description: "This will not be worked on"
  - name: "feature"
    color: "0e8a16"
    description: "New feature"
  - name: "fix"
    color: "d73a4a"
    description: "Bug fix"
  - name: "chore"
    color: "fef2c0"
    description: "Maintenance tasks"
  - name: "dependencies"
    color: "0366d6"
    description: "Pull requests that update a dependency file"
  - name: "security"
    color: "ff0000"
    description: "Security related issues"
  - name: "frontend"
    color: "1d76db"
    description: "Frontend related changes"
  - name: "backend"
    color: "5319e7"
    description: "Backend related changes"
  - name: "database"
    color: "fbca04"
    description: "Database related changes"
  - name: "api"
    color: "c2e0c6"
    description: "API related changes" 